### ISSUE TITLE
Better spacing between Hero and Launch Partners

### ISSUE THREAD

**Issue by orishim** [Web3-API/landing-page#22]
When the window size is smaller, there is not enough space between the first section and the Launch Partner section.

<img width="1322" alt="Screen Shot 2020-11-12 at 2 22 21 PM" src="https://user-images.githubusercontent.com/10736693/98986358-688dc200-24ea-11eb-873d-598da2788c00.png">

**Comment by rihp** [comment]
Look into https://github.com/Web3-API/landing-page/blob/4999706fbe418bbecc55d6a1a5f95820e1aceb8e/index.html#L142

**Comment by rihp** [comment]
Maybe increasing margin to 10px can be a hotfix

https://github.com/Web3-API/landing-page/blob/4999706fbe418bbecc55d6a1a5f95820e1aceb8e/css/web3api.webflow.css#L1218
