### ISSUE TITLE
Refactor website

### ISSUE THREAD

**Issue by rihp** [Web3-API/landing-page#24]
>Task coming from https://github.com/Web3-API/dao/issues/32

The website was initially built with Webflow, which lead us to having a very bloated CSS file.

Right now the site is simple enough that refactoring to a React website with the same appearance and functionality should be a quick task.

The site should keep the same functionality:
 - Email newsletter sign ups
 - Google analytics
 - Responsive/ Mobile friendly 
 - Intro video modal
 - Testimonial Carousel slider

**Comment by dOrgJelli** [comment]
Thanks to @cbrzn @namesty for spearheading this!
